import fs from 'node:fs';
import path from 'node:path';
import * as asar from '@electron/asar';

export function inspectArchive(archive) {
  const pkg = JSON.parse(asar.extractFile(archive, 'package.json').toString());
  if (pkg.name !== 'slack-desktop') throw new Error('Source is not the expected Slack desktop app.');
  const architectureLoader = pkg.main === 'index.js' && (() => {
    const entry = asar.extractFile(archive, 'index.js').toString();
    return /require\(["']electron["']\)/.test(entry) && entry.includes('app.setAppPath(') &&
      entry.includes('process._archPath = require.resolve(') && entry.includes('require(process._archPath)');
  })();
  if (typeof pkg.main !== 'string' || (!pkg.main.endsWith('.cjs') && !architectureLoader)) throw new Error(`Unsupported Slack entry point: ${pkg.main}. Nothing has been changed.`);
  const originalMain = pkg.main.replace(/^\.\//, '');
  if (originalMain.includes('..') || path.isAbsolute(originalMain) || originalMain.startsWith('slack-recent-switcher/')) throw new Error('Use an original, unpatched Slack app as the source.');
  asar.statFile(archive, originalMain);
  return { pkg, originalMain };
}

export async function patchArchive({ archive, output, extracted, root }) {
  const { pkg, originalMain } = inspectArchive(archive);
  asar.extractAll(archive, extracted);
  const unpacked = asar.listPackage(archive).map(name => name.replace(/^[/\\]/, '')).filter(name => {
    const entry = asar.statFile(archive, name, false);
    return !entry.files && entry.unpacked;
  });
  const addon = path.join(extracted, 'slack-recent-switcher');
  fs.cpSync(path.join(root, 'src'), addon, { recursive: true });
  const bootstrap = `// Generated by Slack Recent Switcher.
try {
  const electron = require('electron');
  const path = require('node:path');
  electron.app.setName('Slack Recents');
  if (process.platform === 'linux') electron.app.setDesktopName('local.slackrecents.desktop');
  const profile = path.join(electron.app.getPath('appData'), 'Slack Recents');
  require('node:fs').mkdirSync(profile, { recursive: true });
  electron.app.setPath('userData', profile);
  // Rebuild this copy from an updated official Slack installation to update it.
  if (electron.autoUpdater) {
    electron.autoUpdater.setFeedURL = () => {};
    electron.autoUpdater.checkForUpdates = () => { setImmediate(() => electron.autoUpdater.emit('update-not-available')); };
    electron.autoUpdater.quitAndInstall = () => electron.app.quit();
  }
  require('./runtime.cjs')(electron);
  console.info('[Slack Recents] Installed conversation switcher');
} catch (error) { console.error('[Slack Recents] Startup failed:', error); }
require(${JSON.stringify(`../${originalMain}`)});
`;
  fs.writeFileSync(path.join(addon, 'bootstrap.cjs'), bootstrap);
  pkg.main = './slack-recent-switcher/bootstrap.cjs';
  fs.writeFileSync(path.join(extracted, 'package.json'), JSON.stringify(pkg, null, 2));
  fs.rmSync(output, { force: true });
  fs.rmSync(`${output}.unpacked`, { recursive: true, force: true });
  // Explicit unpack flags avoid platform-specific glob escaping, including
  // backslashes and metacharacters in Windows user/temp directory names.
  const unpackedNames = new Set(unpacked.map(name => name.replaceAll('\\', '/')));
  const streams = [];
  function walk(directory, relative = '') {
    for (const child of fs.readdirSync(directory, { withFileTypes: true })) {
      const file = path.join(directory, child.name);
      const name = path.posix.join(relative, child.name);
      if (child.isDirectory()) {
        streams.push({ path: name, type: 'directory', unpacked: false });
        walk(file, name);
      } else {
        streams.push({ path: name, type: child.isSymbolicLink() ? 'link' : 'file',
          unpacked: unpackedNames.has(name), stat: fs.lstatSync(file),
          streamGenerator: () => fs.createReadStream(file),
          ...(child.isSymbolicLink() ? { symlink: fs.readlinkSync(file) } : {}) });
      }
    }
  }
  walk(extracted);
  // ASAR hashes small stream entries by reading their relative path from cwd.
  // Point it at the extracted archive so a same-named file in this package
  // cannot give the rebuilt archive an incorrect per-file integrity hash.
  const previousCwd = process.cwd();
  try {
    process.chdir(extracted);
    await asar.createPackageFromStreams(output, streams);
  } finally { process.chdir(previousCwd); }
  asar.uncache(output);
  const stored = JSON.parse(asar.extractFile(output, 'package.json').toString());
  if (stored.main !== pkg.main) throw new Error('Archive validation failed.');
  for (const name of unpacked) {
    if (!asar.statFile(output, name).unpacked || !fs.existsSync(path.join(`${output}.unpacked`, name))) throw new Error(`Unpacked file was not preserved: ${name}`);
  }
  return { version: pkg.version, unpacked };
}
