import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { inspectArchive, patchArchive } from './archive.mjs';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const signature = '# Generated by Slack Recent Switcher';
const shellQuote = value => `'${value.replaceAll("'", "'\\''")}'`;
const desktopValue = value => value.replaceAll('\\', '\\\\').replaceAll('\n', '\\n').replaceAll('\r', '\\r');
export function desktopQuote(value) {
  return desktopValue(`"${value.replaceAll('%', '%%').replace(/([\\"`$])/g, '\\$1')}"`);
}
function xdg(name, fallback) { return path.isAbsolute(process.env[name] || '') ? process.env[name] : fallback; }
function resolveSource(value) {
  const candidates = value ? [value] : ['/usr/lib/slack', '/opt/slack', '/usr/bin/slack'];
  for (let candidate of candidates) {
    if (!fs.existsSync(candidate)) continue;
    candidate = fs.realpathSync(candidate);
    if (fs.statSync(candidate).isFile()) candidate = path.dirname(candidate);
    if (/\/(?:snap|flatpak)\//.test(candidate)) continue;
    if (fs.existsSync(path.join(candidate, 'resources/app.asar')) && fs.existsSync(path.join(candidate, 'slack'))) return candidate;
  }
  throw new Error('Original Slack installation not found. Install Slack’s official .deb or .rpm package first, or pass --source /path/to/slack. Snap and Flatpak installations are not supported.');
}
function assertNotRunning(destination) {
  for (const pid of fs.readdirSync('/proc').filter(name => /^\d+$/.test(name))) {
    try {
      if (fs.readlinkSync(`/proc/${pid}/exe`).startsWith(`${destination}/`)) throw new Error('Quit Slack Recents before installing an update.');
    } catch (error) {
      if (!['ENOENT', 'EACCES', 'EPERM'].includes(error.code)) throw error;
    }
  }
}
function checkOwnedFile(file) {
  let stat;
  try { stat = fs.lstatSync(file); } catch (error) { if (error.code === 'ENOENT') return; throw error; }
  if (!stat.isFile() || !fs.readFileSync(file, 'utf8').includes(signature)) throw new Error(`Refusing to replace an unrelated launcher: ${file}`);
}
export async function installLinux(args = []) {
  if (process.getuid?.() === 0) throw new Error('Run the installer as your normal desktop user, without sudo.');
  function argument(name) {
    const index = args.indexOf(name);
    return index < 0 ? undefined : path.resolve(args[index + 1].replace(/^~(?=\/)/, os.homedir()));
  }
  const dataHome = xdg('XDG_DATA_HOME', path.join(os.homedir(), '.local/share'));
  const source = resolveSource(argument('--source'));
  const destination = argument('--destination') || path.join(dataHome, 'slack-recents');
  const marker = path.join(destination, 'resources/slack-recents-install.json');
  const archive = path.join(source, 'resources/app.asar');
  const executable = path.join(destination, 'slack');
  const launcher = path.join(os.homedir(), '.local/bin/slack-recents');
  const desktopFile = path.join(dataHome, 'applications/local.slackrecents.desktop');
  if ([source, destination, launcher, desktopFile].some(value => /[\n\r\0]/.test(value))) throw new Error('Installation paths cannot contain line breaks or NUL characters.');
  if (source === destination || destination.startsWith(`${source}/`) || source.startsWith(`${destination}/`)) throw new Error('Source and destination must be separate directories.');
  if (fs.existsSync(destination) && (fs.lstatSync(destination).isSymbolicLink() || !fs.existsSync(marker))) throw new Error('Destination exists and is not owned by this installer. Choose a different destination.');
  const { pkg } = inspectArchive(archive);
  // Verify the executable architecture before copying hundreds of megabytes.
  const header = Buffer.alloc(20);
  const descriptor = fs.openSync(path.join(source, 'slack'), 'r');
  try { fs.readSync(descriptor, header, 0, header.length, 0); } finally { fs.closeSync(descriptor); }
  if (header.subarray(0, 4).toString('hex') !== '7f454c46' || header[5] !== 1) throw new Error('Slack executable is not a supported Linux ELF binary.');
  const architecture = { 62: 'x64', 183: 'arm64' }[header.readUInt16LE(18)];
  if (architecture !== process.arch) throw new Error(`Slack is ${architecture || 'an unsupported architecture'}, but Node is ${process.arch}. Use a Slack build and Node runtime for the same CPU architecture.`);
  assertNotRunning(destination);
  checkOwnedFile(launcher); checkOwnedFile(desktopFile);
  const backup = `${destination}.previous`;
  if (fs.existsSync(backup)) throw new Error(`Previous backup still exists: ${backup}. Move it before installing again.`);
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  const temporary = fs.mkdtempSync(path.join(path.dirname(destination), '.slack-recents-build-'));
  const staging = path.join(temporary, 'app');
  const previousFiles = new Map([launcher, desktopFile].map(file => [file, fs.existsSync(file) ? { data: fs.readFileSync(file), mode: fs.statSync(file).mode } : null]));
  let installed = false;
  try {
    console.log(`Building Slack Recents from Linux Slack ${pkg.version} (${architecture})…`);
    fs.cpSync(source, staging, { recursive: true, dereference: true });
    await patchArchive({ archive, output: path.join(staging, 'resources/app.asar'), extracted: path.join(temporary, 'archive'), root });
    // Reuse the system-installed sandbox helper; a copied setuid helper would
    // have the wrong owner. Keep Chromium sandboxing enabled in the launcher.
    const sandbox = path.join(source, 'chrome-sandbox');
    const stagedSandbox = path.join(staging, 'chrome-sandbox');
    if (fs.existsSync(stagedSandbox)) {
      fs.unlinkSync(stagedSandbox);
      fs.symlinkSync(sandbox, stagedSandbox);
    }
    fs.writeFileSync(path.join(staging, 'resources/slack-recents-install.json'), JSON.stringify({
      patchVersion: JSON.parse(fs.readFileSync(path.join(root, 'package.json'))).version,
      slackVersion: pkg.version, platform: 'linux', architecture, source, installedAt: new Date().toISOString()
    }, null, 2));
    const launchText = `#!/bin/sh\n${signature}\nexport CHROME_DESKTOP=local.slackrecents.desktop\nexec ${shellQuote(executable)} --class=local.slackrecents "$@"\n`;
    const desktopText = `[Desktop Entry]\n${signature}\nType=Application\nName=Slack Recents\nComment=Slack with recent conversations and custom search\nExec=${desktopQuote(launcher)} %U\nIcon=slack\nTerminal=false\nStartupNotify=true\nStartupWMClass=local.slackrecents\nCategories=Network;InstantMessaging;\nMimeType=x-scheme-handler/slack;\n`;
    if (fs.existsSync(destination)) fs.renameSync(destination, backup);
    try {
      fs.renameSync(staging, destination); installed = true;
      fs.mkdirSync(path.dirname(launcher), { recursive: true });
      fs.mkdirSync(path.dirname(desktopFile), { recursive: true });
      fs.writeFileSync(launcher, launchText, { mode: 0o755 }); fs.chmodSync(launcher, 0o755);
      fs.writeFileSync(desktopFile, desktopText, { mode: 0o644 });
    } catch (error) {
      if (installed) fs.rmSync(destination, { recursive: true, force: true });
      if (fs.existsSync(backup)) fs.renameSync(backup, destination);
      for (const [file, previous] of previousFiles) {
        if (previous) { fs.writeFileSync(file, previous.data); fs.chmodSync(file, previous.mode); }
        else fs.rmSync(file, { force: true });
      }
      throw error;
    }
    fs.rmSync(backup, { recursive: true, force: true });
    spawnSync('update-desktop-database', [path.dirname(desktopFile)], { stdio: 'ignore' });
    const protocol = spawnSync('xdg-mime', ['default', 'local.slackrecents.desktop', 'x-scheme-handler/slack'], { encoding: 'utf8' });
    console.log(`Installed: ${destination}\nLaunch Slack Recents from your applications menu or run:\n${launcher}\nTap Ctrl-K to search; hold Ctrl and cycle K / Shift-K to switch on release.`);
    if (protocol.status !== 0) console.log('To route browser sign-in back to Slack Recents, run: xdg-mime default local.slackrecents.desktop x-scheme-handler/slack');
  } finally { fs.rmSync(temporary, { recursive: true, force: true }); }
}
